### ISSUE TITLE
Image Pull Secrets in ScanTemplates

### ISSUE THREAD

**Issue by nedenwalker** [vrabbi-tap/tap-scanner-integrations#1]
Hi @vrabbi, I see you just added the image pull secret necessary for pulling the container image to be scanned. As it is required for pulling a container image from a private container registry, it is not required for either of the source scan templates or the public image scan. You could remove them from those templates, but as it is, their inclusion shouldn't break anything.

**Comment by vrabbi** [comment]
I just added as per the grype package

**Comment by vrabbi** [comment]
I also added in a seperate commit the changes for env vars in the private image template

**Comment by nedenwalker** [comment]
let me look closer myself then

**Comment by nedenwalker** [comment]
I see, yes, you are correct. You added the targetImagePullSecret to the volumes in private image scan only. I got confused seeing the pull secrets being added to all the templates, but those are different and are needed in each to pull the container image that does the scanning.
